### ISSUE TITLE
Create a !downdetector Parser

### ISSUE THREAD

**Issue by DavidArthurCole** [ServiceNowDevProgram/SlackerBot#101]
- When only `!downdetector` is passed, make use of the [Down Detector API](https://downdetectorapi.com/v2/docs/) to return a list of the most notable "currently down" sites
- When a term is passed `slack`, `discord`, `netflix`, etc., check to see if the page exists (e.g. [https://downdetector.com/status/netflix/](https://downdetector.com/status/netflix/)). If it does, link to the page. If not, link to `https://downdetector.com/search/?q=${term}`

There's probably some more cool stuff that can be done with this one, given they've got a fairly open API.

**Comment by MRSinghRajat** [comment]
I will work on it

**Comment by MRSinghRajat** [comment]
I don't think  Down Detector API are free to use

**Comment by wiz0floyd** [comment]
@MRSinghRajat That appears to be the case. You could still make a useful tool by responding with links. See the XKCD parser or the Wikipedia parser as examples of ones that work without using an api.

**Comment by mjonssonme** [comment]
One can create a parser that pops a link, but it seems harder to parse the page the link produced (via restmessagev2 get) since DownDetector puts a captcha in between. They want to force ppl to the api…

**Comment by hrichiksite** [comment]
https://github.com/ServiceNowDevProgram/SlackerBot/pull/284

I've submitted a base PR for this parser, more to come.
