### ISSUE TITLE
Add a limit to the Lorem Ipsum generator

### ISSUE THREAD

**Issue by johndahl-now** [ServiceNowDevProgram/SlackerBot#110]
The Lorem Ipsum generator does not currently have any limits defined so a user could flood a thread with generated content. Add limits to keep the responses to one Slack message.

Limit to:

- 5 paragraphs
- 500 words
- 5000 bytes

**Comment by ankitshaw625** [comment]
Hi. Can I work on this?

**Comment by johndahl-now** [comment]
Go for it... let me know if you have any questions... I have a thought on this.
