### ISSUE TITLE
Create a !weather parser that takes a location and returns the current or forecast weather

### ISSUE THREAD

**Issue by johndahl-now** [ServiceNowDevProgram/SlackerBot#111]
Given a location and possibly other parameter such as units, or any other options available from the service provider, retrieve and show the weather in Slack.

**Comment by MRSinghRajat** [comment]
I will work on it, any free Weather API Reference?

**Comment by johndahl-now** [comment]
I'm there are several. https://wttr.in works with text.

**Comment by MRSinghRajat** [comment]
@johndahl-now  Thanks i will work on it now
