### ISSUE TITLE
Hacktoberfest parser should reply in a thread

### ISSUE THREAD

**Issue by wiz0floyd** [ServiceNowDevProgram/SlackerBot#120]
Update Hacktoberfest parser to always thread replies.

**Comment by GauthamBellamkonda** [comment]
Sorry for the previous bug, I had checked [this line](https://github.com/ServiceNowDevProgram/SlackerBot/blob/4d7aad9607aba3f1b3ea9fdef0bb7e69b7fc1868/Parsers/Clap%20back.js#L10) from Clap Back.js file and thought that was the right way of doing it.
