### ISSUE TITLE
Fix logic for order and stop_processing

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#121]
@DavidArthurCole graciously took on issue #100 but there were some errors and I had to revert the Parse chat business rule.

Here are some of the errors that I found and tried to fix (I didn't actually solve it, more investigation is needed):

- GlideQuery needed a global tag. `new global.GlideQuery`
- parser should be parsers on `if(parser.stop_processing) break;`
  - alternatively, if we move to glidequery shouldn't we be using a .forEach?
 
Or should we just use the existing gliderecord script and functionality to that?

**Comment by DavidArthurCole** [comment]
I'll take this one on, as I wrote the logic originally. Will do some more thorough testing.
