### ISSUE TITLE
Data retention policy is needed

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#128]
Chats older than 7 days should be purged every night to match the behavior of the old bot application. 

Utilize a system property to determine length of retention (default to 7).

**Comment by chelming** [comment]
_reacts with :trebek: every 7 days for 90 days_ 😎

**Comment by earlduque** [comment]
data retention policy has been implemented on prod. not part of application repo as we figure out a release-agnostic way to do the data deletion
