### ISSUE TITLE
Update XKCD parser to use Blocks

### ISSUE THREAD

**Issue by wiz0floyd** [ServiceNowDevProgram/SlackerBot#159]
Update XKCD parser to use [block kit ](https://api.slack.com/block-kit)for content layout.

**Comment by chelming** [comment]
[Here's a starter for block kit](https://app.slack.com/block-kit-builder/T0E2AD6AY#%7B%22blocks%22:%5B%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Fan%20Theories%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22image%22,%22image_url%22:%22https://imgs.xkcd.com/comics/fan_theories.png%22,%22alt_text%22:%22The%20universe%20fandom%20is%20great.%20Such%20sweet%20and%20enthusiastic%20people.%22%7D,%7B%22type%22:%22context%22,%22elements%22:%5B%7B%22type%22:%22plain_text%22,%22text%22:%22Alt-text:%20The%20universe%20fandom%20is%20great.%20Such%20sweet%20and%20enthusiastic%20people.%22,%22emoji%22:true%7D%5D%7D%5D%7D)

you should be able to build an array from that JSON in block kit builder and pass it right into the text for slack.send (look for all the "yourVariables" in the following.

```javascript
var blocks = [
		{
			"type": "header",
			"text": {
				"type": "plain_text",
				"text": yourVariable.title,
				"emoji": true
			}
		},
		{
			"type": "image",
			"image_url": yourVariable.url,
			"alt_text": yourVariable.altText
		},
		{
			"type": "context",
			"elements": [
				{
					"type": "plain_text",
					"text": "Alt-text: " + yourVariable.altText,
					"emoji": true
				}
			]
		}
	]
var text = {
    "text": "XKCD Parser",
    "blocks": blocks
};
var sendIt = new x_snc_slackerbot.Slacker().send_chat(current, text, false);
