### ISSUE TITLE
convert to binary parser

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#169]

**Comment by Ladirinia** [comment]
Hey there! Just to be sure: You want something like !binary 'Here is the sentence' outputs something like 00100111 01001000 01100101 01110010 01100101 00100000 01101001 01110011 00100000 01110100 01101000 01100101 00100000 01110011 01100101 01101110 01110100 01100101 01101110 01100011 01100101 00100111, correct?

**Comment by earlduque** [comment]
@Ladirinia that's right!

**Comment by RaunakScarlet** [comment]
may i work on this

**Comment by Ladirinia** [comment]
Hey Raunak: Already started, not sure if you can use any of this: 

/*
activation_example:!binary Hello my name is
regex:!binary
flags:g
*/


var term = current.text.split('!binary')[1].trim();
var msg = term+' in binary is: '+ binary(term);

new x_snc_slackerbot.Slacker().send_chat(current, msg, false);
new x_snc_slackerbot.Slacker().send_reaction(current,'robot_face');


function binary(term) {
    var result = "";
    for (var i = 0; i <= term; i++) {
        result += string.charCodeAt(i).toString(2);
        }
    return result;
}

It does return a binary string, but however, as far as online converters showed it does not seem to be right (read up a little bit on padding and similar issues) - feel free to either use or throw it :)
