### ISSUE TITLE
Update !xkcd parser to include a link

### ISSUE THREAD

**Issue by wiz0floyd** [ServiceNowDevProgram/SlackerBot#195]
Update the XKCD parser to include a link to the comic.

**Comment by chelming** [comment]
also add code to change the title of https://xkcd.com/1015/ to `Keming`

**Comment by chelming** [comment]
(that was a joke)

**Comment by wiz0floyd** [comment]
Could also add random functionality. Not sure what the best way is to accomplish that.

**Comment by SapphicFire** [comment]
Split random suggestion to a separate story
