### ISSUE TITLE
Add functionality that allows slack admins to store information about a user that can be viewed by other users

### ISSUE THREAD

**Issue by wiz0floyd** [ServiceNowDevProgram/SlackerBot#210]
Create a command that lets admins store information about a user (e.g. confirmation that they are an employee of ServiceNow) and another command that allows all users to view the stored information.

**Comment by eriemer1** [comment]
I like this, and can see a good way to make the second part work (i.e. !dox @user)
I can't think of a good way to deal with the adding or editing data from slack. I want to say that the SNDevs Admins should log into the instance and either edit things directly there or have a portal page/catalog item to look up a user and add/edit the custom info

**Comment by chelming** [comment]
`!verify @user` - see if they're verified

`!verify-admin add @user` - add a user to the verified table

`!verify-admin remove @user` - remove a user from the verified table 🤷
