### ISSUE TITLE
when someone says "so extra" or "i'm extra" or "e x t r a" react with emoji

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#211]
![image](https://github.com/ServiceNowDevProgram/SlackerBot/assets/31702109/324fa9df-d9c3-4b58-95ae-c23600011db7)
action-left
alphabet-white-e
alphabet-white-x
alphabet-white-t
alphabet-white-r
alphabet-white-a
action-right

**Comment by chelming** [comment]
@earlduque ++

**Comment by earlduque** [comment]
I am going to try to do  this
