### ISSUE TITLE
Auto react with a Vancouver emoji when someone says Vancouver

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#214]
similar to #197 but for Vancouver:

but we need someone to upload a vancouver emoji first to the workspace. once that's done, create a parser:
reacts with the :vancouver: emoji whenever someone says vancouver **as a standalone word**

**Comment by RaunakScarlet** [comment]
please assign me...i'm working on it

**Comment by RaunakScarlet** [comment]
is this emoji fine?

although it is like chat but i will add to reaction

<img width="754" alt="Screenshot 2023-10-02 at 12 24 53 AM" src="https://github.com/ServiceNowDevProgram/SlackerBot/assets/86217548/f845c10e-3798-4b7c-a428-31994f1c997e">

**Comment by RaunakScarlet** [comment]
added to reaction 

<img width="749" alt="Screenshot 2023-10-02 at 1 52 54 AM" src="https://github.com/ServiceNowDevProgram/SlackerBot/assets/86217548/24bdf897-232a-4463-8e11-d317e7b284fe">
