### ISSUE TITLE
Fix utah react parser

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#215]
https://github.com/ServiceNowDevProgram/SlackerBot/blob/35793fc86ba7b320090fecfc6df40aaad10a3eb3/Parsers/Utah%20triggers%20Utah%20react.js

As found in #213, this parse doesn't work as expected because Slack interprets #utah as a channel call and changes the text to the unique ID of the channel, so the parser never actually sees the word "utah" and thus never runs

![image](https://github.com/ServiceNowDevProgram/SlackerBot/assets/31702109/bb60d49b-5c9a-4a68-b2c3-b81e09d15276)

Change this parser so that it runs whenever someone says utah **as a standalone word**

**Comment by Ladirinia** [comment]
Happy to take this one over (this time in October :p). Just to be sure, by standalone you mean utah surrounded by two spaces, right? Such as We use utah now? Or really simply whenever in any sentence utah is mentioned, including such as xyutahyx?

**Comment by earlduque** [comment]
it's a way to do regex, actually!

![image](https://github.com/ServiceNowDevProgram/SlackerBot/assets/31702109/d46a00af-6d86-4259-b3cd-7c46e89220ab)

putting \b before and after your word basically says "there should be a word boundary here" not another letter.
Spaces _could_ work but doing word boundaries also factors for things like punctuation or newlines

**Comment by earlduque** [comment]
i'm going to assign this to you @Ladirinia but really, wait til 5pm Pacific tomorrow! then you can get credit!

**Comment by Ladirinia** [comment]
Thank you!! :) And thanks for sharing your knowledge!
