### ISSUE TITLE
Auto react with a Washington emoji when someone says Washington 

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#216]
similar to #214 but for Vancouver:

but we need someone to upload a Washington emoji first to the workspace. once that's done, create a parser:
reacts with the :washington: emoji whenever someone says washington as a standalone word

**Comment by Ladirinia** [comment]
Hey there! How can I (create and) upload an emoji to the workspace? 😅 Maybe we can take this one? Looks cute to me and seems to be free: https://www.emojipng.com/preview/11017498

**Comment by earlduque** [comment]
![image](https://github.com/ServiceNowDevProgram/SlackerBot/assets/31702109/b9fdbcc8-bb39-4985-a261-6e4f0faa0b25)

**Comment by RaunakScarlet** [comment]
hey @Ladirinia ,
Are u working on it?

**Comment by Ladirinia** [comment]
Yes, uploaded the emoji and will write the parser today! :)

Raunak Scarlet ***@***.***> schrieb am Di., 3. Okt. 2023,
09:23:

**Comment by SapphicFire** [comment]
Hi @Ladirinia, any progress here? Let us know if we should I assign so others know they can pick it up

**Comment by RaunakScarlet** [comment]
i'm ready to pick it

**Comment by Ladirinia** [comment]
Hey there, I opened a pull request which got rejected and didn't have the time to follow up so far, but would be free to do it this weekend. Anyways, as I do not think four pull requests are too realistic for me anymore, feel free to pick it @RaunakScarlet.

**Comment by Ladirinia** [comment]
/*
activation_example: Please check the washington channel
regex:\bwashington\b
flags:gmi
order:200
stop_processing:false
*/

new x_snc_slackerbot.Slacker().send_reaction(current,'washington');

This should do the trick, feel free to use it.
