### ISSUE TITLE
Add functionality to make it so that some commands do not appear in !help

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#225]
the parser list grows (as we hoped for!)

we should add a field to the parser table, like "include in help" or something, and then default it to true. then in the future we can add a help:false flag in each parser template.

then we would want to update the !help command to check for the flag.

**Comment by RaunakScarlet** [comment]
i'm working on it

**Comment by RaunakScarlet** [comment]
i made the fearure and its in PR

**Comment by SapphicFire** [comment]
Issue resolved by PR
