### ISSUE TITLE
Fix regex for affirm parser

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#241]
The regex flag on the header is incorrect
`!affirm, !affirm @user`
should be just `!affirm`, otherwise it's looking for the exact literal string "!affirm, !affirm @user"

dropping the !affirm @user part seems fine too because the parser doesn't seem to be trying to do anything with the username anyways

**Comment by ajcooper72** [comment]
I'll fix this up now.

**Comment by SapphicFire** [comment]
Closing as @ajcooper72 has addressed
