### ISSUE TITLE
!dalle is broken

### ISSUE THREAD

**Issue by chelming** [ServiceNowDevProgram/SlackerBot#296]
Daviiiiiiiiiiiiiiid

**Comment by chelming** [comment]
@DavidArthurCole

**Comment by DavidArthurCole** [comment]
No (:

Make a centralized account please - I don't want to keep re-creating imgur albums to fix this every so often

**Comment by chelming** [comment]
@DavidArthurCole but you're the center of my universe. it can't get _more_ centralized than it currently is.
