### ISSUE TITLE
Add functionality to !summarize that allows it to be used outside of a thread

### ISSUE THREAD

**Issue by wiz0floyd** [ServiceNowDevProgram/SlackerBot#300]
This new functionality should summarize based on an input parameter for an amount of time. Set an upper bound for the number of messages used to generate the summary.

`!summarize 1 hour`

**Comment by earlduque** [comment]
i made it do 30 minutes as hardcoded to avoid people abusing it with long time limits and to not deal with the complexity of figuring out a dynamic way to parse duration for the endocded query
