### ISSUE TITLE
Update !hacktoberfest for 2024

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#332]
https://github.com/ServiceNowDevProgram/SlackerBot/blob/main/Parsers/Hacktoberfest.js needs to be brought up to date

**Comment by ShatilKhan** [comment]
Hi I don't see a hacktoberfest tag here @earlduque 
if it's up for grab, I'd like to take it, with the hacktoberfest tag

**Comment by earlduque** [comment]
I've assigned it to you, we don't normally label the issues with Hacktoberfest tags because almost all of these projects are for Hacktoberfest entirely so all issues can be worked on at will, thank you for checking though!

**Comment by Beeram12** [comment]
@earlduque May I know the pull request I made will be considered for hacktoberfest 2024 ?
