### ISSUE TITLE
Incorporate ES12 support into Slacker's scope

### ISSUE THREAD

**Issue by SapphicFire** [ServiceNowDevProgram/SlackerBot#356]
## Current State

SlackerBot is running on ES5 Standards Mode by virtue of when this application was built. ES12 support is now available to scoped applications

## Requirements to change

While changing the JS Mode is as simple as updating a choice list, I would suggest the person who takes on this issue test that the parsers and SRAPIs function as expected to ensure we don't lose service in updating the app

## Next steps

Once this is updated, please reach out to @SapphicFire or @earlduque or @wiz0floyd to get this update to the application reflected on the DPR instance.

**Comment by earlduque** [comment]
We did it live ¯\_(ツ)_/¯
