### ISSUE TITLE
Update Chuck parser to randomize between the different chuck emojis

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#36]
https://github.com/ServiceNowDevProgram/SlackerBot/blob/main/Parsers/Bowtie%20when%20chuck%20is%20mentioned.js

:bowtie:
:chuck-le:
:chuck-point:
:thinking-chuck:
:upsidedown-chuck:
:thinking-chuck-cartoon:

**Comment by wiz0floyd** [comment]
Assign to me please

**Comment by earlduque** [comment]
#37
