### ISSUE TITLE
Translate parser not working

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#379]
https://github.com/ServiceNowDevProgram/SlackerBot/blob/main/Parsers/Translator.js from #367 isn't working for example prompts, does not create system logs and the error chats aren't going through either.

**Comment by sanjay7178** [comment]
@earlduque can you assign for this issue

**Comment by ariyadmir** [comment]
The translation API used here has connection issues, resulting in unsuccessful requests. I've updated the code and switched to another API. Please review the changes. Thanks a lot!
