### ISSUE TITLE
Random number parser breaks the bot

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#380]
https://github.com/ServiceNowDevProgram/SlackerBot/blob/main/Parsers/Random%20Number%20generator.js
from #377

I should have caught this on review, but the header template is not formatted correctly at all. it has leading spaces after every :. we do not .trim() this field because spaces are legitimate characters for regex.

needs to be fixed and the set back to active:true

**Comment by soham-shee** [comment]
Hey @earlduque, can you assign this issue to me. I think I will be able to fix this.

**Comment by ashoo-jindal** [comment]
Please assign this issue to me. I will fix this.
