### ISSUE TITLE
!reverse doesn't work

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#410]
i'm guessing either make this an array of strings then join them, or change it to a template literal

https://github.com/ServiceNowDevProgram/SlackerBot/blob/main/Parsers/Reverse.js

![image](https://github.com/user-attachments/assets/48771136-1f99-4b2f-988b-93d178d57140)

**Comment by watrick** [comment]
Thanks for the catch! I should test these things ahead of time but trying to avoid the hard route for now.

**Comment by earlduque** [comment]
resolved by #411
