### ISSUE TITLE
Rename parser filenames to be more helpful

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#45]
the !help command prints this:
`!bang @person` bang
`!clap your sentence` Clap back
`!docs GlideRecord` docs
`!help` All Commands
`!iss` International Space Station
`!jitsi` jitsi
`!send !random !hey` Admin tool - Send
`!Tips` Tips for Slack
`!trout Helming` trout
`!whois @EarlDuque` Admin tool - Whois
`!wiki ServiceNow` Search Wikipedia(en)
`!xkcd wisdom of the ancients` xkcd
`30c or 30 degrees celcius` C to F Converter
`30f or 30f degrees celcius` F to C Converter
`@Chuck.Tomasi` Bowtie when chuck is mentioned
`happy pride` pride-reaction
`parrotwave` Parrot Wave chat trigger

the format is:
`activation_example` filename
Note: filename without the .js

Rename all filenames (and if needed, fix their activation examples) to have a better description for the !help command

for example:
rename `xkcd.js` to `Find a relevant XKCD comic.js`

**Comment by johndahl-now** [comment]
I'll take this.

**Comment by earlduque** [comment]
#60
