### ISSUE TITLE
`Parrot wave` is duplicated and missing an activation_example.

### ISSUE THREAD

**Issue by johndahl-now** [ServiceNowDevProgram/SlackerBot#66]
There are two parsers that provide similar "Parrot Wave" behavior and both have incomplete headers as described as mandatory in the contributing.md file.

**Comment by earlduque** [comment]
They are different. One is for chat parsing and one is a trigger for emoji reacts based on new documentation added to the contributing file a couple nights ago. The new template only needs one header
