### ISSUE TITLE
Re-organize duplicated content in readme and contributing

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#69]
The two documentation files currently have duplicated sections that appear in both, this should probably be fixed so that contributors dont get confused. 

Readme probably should have almost everything from description to apis and installation instructions. While contributing has only requirements for contributors to get their pull requests approved. 

Maybe verify that split is standard best practice for GitHub

**Comment by johndahl-now** [comment]
Does it also make sense to remove the "easy" part? The only difference is where the changes are made and pull requests are submitted. Testing still requires pulling the app into a PDI, setting up a personal Slack instance, and setting up the integrations.

**Comment by earlduque** [comment]
> Does it also make sense to remove the "easy" part? The only difference is where the changes are made and pull requests are submitted. Testing still requires pulling the app into a PDI, setting up a personal Slack instance, and setting up the integrations.

@johndahl-now it's a great question. I know enough about the bot and the workings of the app that I can confidently recognize if *simple* parsers will work or not without parsing. This will allow people who don't know the actual ServiceNow side to be able to contribute just by following documentation.
