### ISSUE TITLE
Create an !ice breaker parser

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/SlackerBot#74]
something like: when someone says !ice breaker, the bot responds with a random "get to know each other" prompt.
example responses
- how many siblings do you have, 
- what's your favorite movie, 
- what do you do for fun, 
- would you rather fight 100 duck-sized horses or 1 horse-sized duck?

**Comment by JWITSM** [comment]
I will create this parser.

**Comment by DavidMarcial** [comment]
@earlduque or @wiz0floyd can I get this assigned to me?
