### ISSUE TITLE
Create a !lorem parser to generate Lorem Ipsum text

### ISSUE THREAD

**Issue by johndahl-now** [ServiceNowDevProgram/SlackerBot#79]

**Comment by MRSinghRajat** [comment]
I am working on it.

**Comment by earlduque** [comment]
To elaborate, "Lorem Ipsum" is known more commonly as [filler text](https://www.lipsum.com/)
In a parser for Lorem Ipsum text, the bot should generate random filler text when called. It can do so completely randomly (deciding length and/or which words at random) or it can be programed to accept parameters such `!lorem 10` to give 10 filler words.

**Comment by MRSinghRajat** [comment]
Is there any Maximum Value to it?

**Comment by earlduque** [comment]
> Is there any Maximum Value to it?

It's up to the creator. I think it'd be a good idea to put a maximum on it. I know for the dice roll feature I put a cap on it just to prevent spam.

**Comment by johndahl-now** [comment]
@MRSinghRajat rather than hard-coding a string, you might consider the `RESTMessageV2` API to pull text from a site that generates the Lorem Ipsum text. `https://www.lipsum.com/` has a feed available that you can use with parameters to determine how much to generate. This feed accepts parameters in paragraphs, words, or bytes. I might change the default to 1 paragraph and, as @earlduque suggested, add a limit of some reasonable value... say 4-5 paragraphs.

Good luck and enjoy the Hacktoberfest challenge... I know I am!

**Comment by MRSinghRajat** [comment]
@johndahl-now  is it ok it uses http://asdfast.beobit.net/docs/ API?

**Comment by johndahl-now** [comment]
That's up to @earlduque as he is the repo owner and judge. I'm not familiar with that particular API. Lipsum is very simple so I haven't had a need to look elsewhere.

**Comment by johndahl-now** [comment]
The lipsum site is very simple... it's a `get` call that takes 3 query parameters, what ('bytes', 'words', 'paras'), amount (integer), and start (true/false).

This URL will provide 6 paragraphs that start with the "standard" text "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

https://www.lipsum.com/feed/json?start=yes&amount=6&what=paras
