### ISSUE TITLE
Create a Slack App Manifest for SlackerBot

### ISSUE THREAD

**Issue by DavidArthurCole** [ServiceNowDevProgram/SlackerBot#83]
Create an [app manifest](https://api.slack.com/reference/manifests) to make pulling SlackerBot into a new workspace easier.

For the manifest itself, follow configuration settings listed in the [README](https://github.com/ServiceNowDevProgram/SlackerBot/blob/main/README.md#installing-this-bot-on-your-own-slack-server).

**Comment by DavidArthurCole** [comment]
Just submitted this for tracking, and in case I can't get it right.

I'll be taking a crack at this one tonight.

**Comment by DavidArthurCole** [comment]
After a further look, looks like manifests can be exported from _existing_ applications, and given that SlackerBot in the SNDevs Slack should likely be the authoritative starting point, the manifest should probably be exported from the app, and added to the repo.

**Comment by earlduque** [comment]
i guess i should assign this to myslef then 🤷🏼
